use super::listeners::current_uid;
use crate::models::{Endpoint, ProcessInfo, ProjectInfo, ServiceSnapshot, WorkspaceSnapshot};

pub(crate) fn demo_snapshot() -> WorkspaceSnapshot {
    let now = crate::models::now_epoch();
    let project = |id: &str, name: &str, path: &str| ProjectInfo {
        id: id.into(),
        name: name.into(),
        root_path: path.into(),
        detection_source: "package.json".into(),
        workspace_root_path: path.into(),
        workspace_name: name.into(),
    };
    let service = |id: &str,
                   name: &str,
                   tech: &str,
                   category: &str,
                   port: u16,
                   path: &str,
                   age: u64,
                   origin_kind: &str,
                   origin: &str| ServiceSnapshot {
        id: id.into(),
        display_name: name.into(),
        tech: tech.into(),
        category: category.into(),
        relevance: "dev".into(),
        endpoints: vec![Endpoint {
            family: "IPv4".into(),
            address: "127.0.0.1".into(),
            port,
            scope: "loopback".into(),
            protocol: "TCP".into(),
        }],
        process: Some(ProcessInfo {
            pid: 20_000 + port as u32,
            parent_pid: Some(1000),
            name: tech.into(),
            executable: Some(format!("/usr/local/bin/{tech}")),
            working_directory: Some(path.into()),
            command: format!("{tech} run --port {port}"),
            launch_command: Some(format!("{tech} run --port {port}")),
            create_time: now.saturating_sub(age),
            uptime_seconds: age,
            cpu_percent: Some(1.4),
            memory_bytes: Some(146_800_640),
            uid: current_uid(),
        }),
        project: Some(project(
            &format!("project-{id}"),
            path.rsplit('/').next().unwrap_or(name),
            path,
        )),
        status: "healthy".into(),
        warnings: vec![],
        origin_kind: origin_kind.into(),
        origin_label: Some(origin.into()),
        can_terminate: false,
        browser_url: Some(format!("http://localhost:{port}")),
        active_profiles: Vec::new(),
    };
    let services = vec![
        service(
            "demo-api",
            "cutting-board-api · Spring Boot",
            "spring",
            "api",
            8080,
            "/Users/shane/Developer/cutting-board-api",
            94,
            "ide",
            "IntelliJ IDEA",
        ),
        service(
            "demo-web",
            "cutting-board-web · Vite",
            "vite",
            "web",
            5173,
            "/Users/shane/Developer/cutting-board-web",
            3725,
            "agent",
            "Agent",
        ),
        service(
            "demo-db",
            "local-postgres",
            "postgresql",
            "database",
            5432,
            "/Users/shane/Developer/local-stack",
            86_400,
            "terminal",
            "iTerm2",
        ),
        service(
            "demo-cache",
            "local-redis",
            "redis",
            "cache",
            6379,
            "/Users/shane/Developer/local-stack",
            710,
            "terminal",
            "iTerm2",
        ),
    ];
    WorkspaceSnapshot {
        endpoint_count: services.len(),
        services,
        scanned_at: now,
        scan_duration_ms: 18,
        errors: vec![],
    }
}
